### ISSUE TITLE
`download_external_modules` and `log_level` are not allowable inputs

### ISSUE THREAD

**Issue by olivierlefloch** [bridgecrewio/bridgecrew-action#18]
The documentation suggests I can increase logging level by setting `log_level: DEBUG`, but when I do so, I get informed that:

> Warning: Unexpected input(s) 'log_level', valid inputs are ['entryPoint', 'args', 'directory', 'check', 'skip_check', 'quiet', 'api-key', 'soft_fail', 'external_checks_dir', 'output_format']

I believe this is also a problem with `download_external_modules`.

**Comment by rafaeelaudibert** [comment]
I think this issue might be closed because of #19 @mikeurbanski1

**Comment by danielvincenzi** [comment]
He forgot to add in the patch the `download_external_modules` parameter as args in the Docker call and it still doesn't work...
+ @mikeurbanski1
+ @rafaeelaudibert
