### ISSUE TITLE
[Alignment Bug] CTA button are aligned to the center instead of left. 

### ISSUE THREAD

**Issue by rohiraanjali** [bridgecrewio/bridgecrew-action#22]
Call to Action buttons at bridgecrew.io are aligned to the center when the text around it is aligned to left. This looks like an alignment issue. 
![Screenshot (24)](https://user-images.githubusercontent.com/74822422/135745238-cf9fff6e-906d-4898-8b35-6b26de8e7ca1.png)
Can be fixed by: 
CSS: 
.cta-row--center {
text-align: left;
}

**Comment by tsmithv11** [comment]
Thank you for the feedback, but this feedback is for our website not our GitHub Action.
