### ISSUE TITLE
Warning: No files were found with the provided path: results.sarif. No artifacts will be uploaded.

### ISSUE THREAD

**Issue by chadatprimer** [bridgecrewio/bridgecrew-action#24]
Just a heads up - lots of folks are experiencing failures (us included) when trying to use the github action for bridgecrew. https://github.com/mikeurbanski1/azure-tf/actions/runs/661611939 as an example.

This is an output from one of my repos:

```
Run actions/upload-artifact@v2
  with:
    name: SARIF results
    path: results.sarif
    if-no-files-found: warn
Warning: No files were found with the provided path: results.sarif. No artifacts will be uploaded.
1s
Run github/codeql-action/upload-sarif@v1
Error: Path does not exist: results.sarif
Error: Path does not exist: results.sarif
    at getSarifFilePaths (/tmp/github-runner/_actions/github/codeql-action/v1/lib/upload-lib.js:144:15)
    at Object.uploadFromActions (/tmp/github-runner/_actions/github/codeql-action/v1/lib/upload-lib.js:132:30)
    at run (/tmp/github-runner/_actions/github/codeql-action/v1/lib/upload-sarif-action.js:49:46)
    at async runWrapper (/tmp/github-runner/_actions/github/codeql-action/v1/lib/upload-sarif-action.js:63:9)
```

I used the file from [here](https://github.com/bridgecrewio/bridgecrew-action/blob/master/examples/code_scanning.yml)

**Comment by chadatprimer** [comment]
As a test I copied the yaml directly from here in a new repo: https://docs.bridgecrew.io/docs/setup-github-code-scanning

I can see in the action log that there were findings, but I still have the same message as above.

Additionally, **none** of the findings are in the Projects, Incidents, or Code Review sections of the web console - though I do see that the repo has been added.

**Comment by kartikp10** [comment]
Hey @chadatprimer hopefully this PR should address this issue. Thanks for your patience.
