### ISSUE TITLE
checkov-action vs. bridgecrew-action

### ISSUE THREAD

**Issue by chrillep** [bridgecrewio/bridgecrew-action#32]
just out of curiosity. whats the difference between

[bridgecrewio/bridgecrew-action](https://github.com/bridgecrewio/bridgecrew-action)
and 
[bridgecrewio/checkov-action](https://github.com/bridgecrewio/checkov-action)

?

can't seem to find it in any docs.

**Comment by schosterbarak** [comment]
Hey @chrillep thanks for reaching out. Historically there was a difference but today, with the usage of bridgecrew API key they are the same and serve the same purpose.

**Comment by chrillep** [comment]
aah great thanks! :)
