### ISSUE TITLE
Authentication error with latest changes

### ISSUE THREAD

**Issue by jgeurts** [bridgecrewio/bridgecrew-action#39]
What was working previously, I'm now getting the following error:

```
Error: -04 16:04:54,526 [MainThread  ] [ERROR]  Received an error response during authentication
Error: -04 16:04:54,527 [MainThread  ] [ERROR]  An error occurred setting up the Bridgecrew platform integration. Please check your API token and try again.
Error: -04 16:04:54,527 [MainThread  ] [ERROR]  Please try setting the environment variable LOG_LEVEL=DEBUG and re-running the command, and provide the output to support
```

Can you please create releases for this action so that we can pin to specific versions in our code?

**Comment by gruebel** [comment]
hey @jgeurts thanks for reaching out.
we create for each upgrade a tag, which you can reference https://github.com/bridgecrewio/bridgecrew-action/tags
your error has nothing to do with the version of the GHA, you can try to create a new token. If this doesn't help, then we need more info, like your Bridgecrew organization name and you use the default URL or did you override with a different region?

**Comment by jgeurts** [comment]
ah, gotcha, I missed the tags. Thank you! 

I tried a new token when things stopped working but I'm seeing the same issue. Is there a preferred support channel I can reach out to for this?

**Comment by nimrodkor** [comment]
Can you please add an env variable:
```
LOG_LEVEL: DEBUG
```
to the action and share the resulting logs? @jgeurts 

You can also share our slack workspace via [slack.bridgecrew.io](slack.bridgecrew.io)

**Comment by jgeurts** [comment]
@nimrodkor [this](https://github.com/bridgecrewio/bridgecrew-action/issues/39#issuecomment-1371131516) comment was the debug output, as far as I can tell.

**Comment by jgeurts** [comment]
Seems this is not related to the action. That said, I have no idea how to get the api token configured and there was no help with that, so I have moved on without Bridgecrew
